layout = {
    "expedition_date":"a data de emissão do presente documento retorne no formato dd/mm/aaaa",
    "responsible_registry":"nome do cartório que emitiu o documento",
    "registration_number":"Número da matrícula do imóvel",
    "property_type":"Tipo do imóvel (lote, prédio residencial, apartamento, terreno, vaga de garagem) IMPORTANTE: converta 'terreno urbano' é a mesma coisa que 'terreno' então retorne 'terreno' se o tipo for 'terreno urbano'; IMPORTANTE: no caso de prédio e respectivo terreno sempre retorne prédio;",
    "batch":"apenas o lote do terreno, indique se é o lote inteiro ou se é partes ou parte do lote;",
    "block":"a quadra do imóvel (se houver, somente número/nome da quadra)",
    "street":"A primeira rua do imóvel, escrever no começo se é rua, avenida, etc",
    "street_2":"A segunda rua do imóvel, escrever no começo se é rua, avenida, etc",
    "property_number":"sempre que houver, pegar o primeiro número do endereço do imóvel",
    "property_number_2":"sempre que houver, pegar o segundo número do endereço do imóvel",
    "address_complement":"o número do apartamento, número do bloco ou número da vaga de garagem. IMPORTANTE: SOMENTE o número;",
    "neighborhood":"pegar APENAS o bairro onde fica localizado o imóvel",
    "city":"pegar APENAS a cidade onde fica localizado o imóvel",
    "state":"estado onde o imóvel fica localizado retorne o nome COMPLETO do estado",
    "property_footage":"pegar APENAS o primeiro tamanho do imóvel que encontrar e remover a unidade de medida",
    "owners_quantity":"Quantidade de donos ATUAIS do imóvel, retorne como número",
    "owner_1":"Nome Completo do primeiro proprietário",
    "owner_2":"Nome Completo do segundo proprietário (se houver)",
    "document_owner_1":"CPF ou CNPJ do proprietário principal (PADRÃO CPF: 000.000.000-00) (PADRÃO CNPJ: 00.000.000/0000-00)",
    "document_owner_2":"CPF ou CNPJ do proprietário secundário (se houver) (PADRÃO CPF: 000.000.000-00) (PADRÃO CNPJ: 00.000.000/0000-00)",
    "mortgage":"Indique se o imóvel está em hipoteca (sim ou não) retorne sim ou não",
    "mortgage_owner_name":"Nome do dono da hipoteca (se houver)",
    "mortgage_owner_document":"CPF ou CNPJ do proprietário da hipoteca (se houver)",
    "fiduciary_alienation":"Indique se o imóvel está em alienação fiduciária (sim ou não) retorne sim ou não",
    "fiduciary_alienation_owner_name":"Nome do dono da alienação fiduciária (se houver)",
    "fiduciary_alienation_owner_document":"CPF ou CNPJ do proprietário da alienação fiduciária (se houver) (PADRÃO CPF: 000.000.000-00) (PADRÃO CNPJ: 00.000.000/0000-00)",
    "garnishment":"Indique se o imóvel está em penhora (sim ou não) retorne sim ou não"
 }